name: 'Add existing app or test app'

run-name: "Add existing app or test app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      url:
        description: Direct Download Url of .app or .zip file
        required: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for PR/Commit?
        type: boolean
        default: false

permissions:
  actions: read
  contents: write
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  AddExistingAppOrTestApp:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Dump Workflow Information
        uses: cegekaJG/AL-Go-Actions/DumpWorkflowInfo@testbranch6
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Initialize the workflow
        id: init
        uses: cegekaJG/AL-Go-Actions/WorkflowInitialize@testbranch6
        with:
          shell: powershell

      - name: Read settings
        uses: cegekaJG/AL-Go-Actions/ReadSettings@testbranch6
        with:
          shell: powershell

      - name: Read secrets
        id: ReadSecrets
        uses: cegekaJG/AL-Go-Actions/ReadSecrets@testbranch6
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Add existing app
        uses: cegekaJG/AL-Go-Actions/AddExistingApp@testbranch6
        with:
          shell: powershell
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          project: ${{ github.event.inputs.project }}
          url: ${{ github.event.inputs.url }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: cegekaJG/AL-Go-Actions/WorkflowPostProcess@testbranch6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
